import type { Metadata } from "next";
import {
  Plus_Jakarta_Sans,
  Playfair_Display,
  Unbounded,
} from "next/font/google";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});
export const bitcountGridDouble = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["600"],
});

export const metadata: Metadata = {
  title: "HASHTAG FAISAL | The Humanoid Email Marketer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} bg-secondary text-primary leading-normal scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
